site:
  title: "通勤AIニュース"
  author: "SEITOSHIKI"
  language: "ja"
  # FEED_BASE_URL が未設定のとき scripts/main.py が自動推定（GitHub PagesのURL）します
  base_url: null
  description: "通勤向け：AI関連ニュースの音声ダイジェスト（日本語）"

schedule:
  target_total_minutes: 60
  per_item_seconds_min: 90
  per_item_seconds_max: 360
  max_items: 18

sources:
  google_news_queries:
    - "AI OR 人工知能 when:1d"
    - "LLM OR 大規模言語モデル when:1d"
    - "生成AI OR ジェネレーティブ when:1d"
    - "松尾研究室 when:7d"
    - "落合陽一 OR Yoichi Ochiai when:7d"
    - "multi-agent OR 自律エージェント when:7d"
    - "prompt engineering OR プロンプト エンジニアリング when:7d"
  extra_rss:
    - "https://www.technologyreview.jp/feed/"
    - "https://the-decoder.com/en/feed/"

filters:
  must_include_any:
    - "AI"
    - "人工知能"
    - "生成AI"
    - "LLM"
  must_exclude_any:
    - "セール"
    - "広告"
    - "求人"

summary:
  style: "友達に話す口調で、要点→背景→技術→影響→一言の順。略語は“単語をそのまま”読み、URLは絶対に発話しない。"
  max_chars_per_item: 900
  temperature: 0.35
  include_source: false

tts:
  provider: "openai"
  model: "gpt-4o-mini-tts"
  voice: "alloy"
  speaking_rate: 1.05
  chunk_chars: 800
  output_bitrate: 128

output:
  keep_days: 14
