name: Build & Publish AI Commute Audio

on:
  workflow_dispatch:
  schedule:
    # JST 05:00 = UTC 20:00（前日）
    - cron: "0 20 * * *"

permissions:
  contents: write

concurrency:
  group: "ai-commute-audio"
  cancel-in-progress: false

env:
  PYTHONUNBUFFERED: "1"

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ffmpeg & espeak-ng
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg espeak-ng

      - name: Generate audio & feed
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FEED_BASE_URL: ${{ secrets.FEED_BASE_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python -m scripts.main

      # GitHub Pages を「ブランチ配信」にする想定
      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          # 既存履歴が壊れている場合は有効化（初回のみ）
          # force_orphan: true
